application: hack-tj
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url:  /((.)*(/)?)?
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "latest"

- name: pycrypto
  version: "latest"

- name: PIL
  version: "latest"
